/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultorRouteImport } from './routes/consultor'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as ViaturasIndexRouteImport } from './routes/viaturas.index'
import { Route as ViaturasSlugRouteImport } from './routes/viaturas.$slug'
import { Route as ApiPublicFotoSplatRouteImport } from './routes/api/public/foto/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorRoute = ConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/imoveis/$slug',
  path: '/imoveis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ViaturasIndexRoute = ViaturasIndexRouteImport.update({
  id: '/viaturas/',
  path: '/viaturas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViaturasSlugRoute = ViaturasSlugRouteImport.update({
  id: '/viaturas/$slug',
  path: '/viaturas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFotoSplatRoute = ApiPublicFotoSplatRouteImport.update({
  id: '/api/public/foto/$',
  path: '/api/public/foto/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultor': typeof ConsultorRoute
  '/contacto': typeof ContactoRoute
  '/sobre': typeof SobreRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/viaturas/$slug': typeof ViaturasSlugRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/viaturas/': typeof ViaturasIndexRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultor': typeof ConsultorRoute
  '/contacto': typeof ContactoRoute
  '/sobre': typeof SobreRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/viaturas/$slug': typeof ViaturasSlugRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/viaturas': typeof ViaturasIndexRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultor': typeof ConsultorRoute
  '/contacto': typeof ContactoRoute
  '/sobre': typeof SobreRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/viaturas/$slug': typeof ViaturasSlugRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/viaturas/': typeof ViaturasIndexRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultor'
    | '/contacto'
    | '/sobre'
    | '/imoveis/$slug'
    | '/viaturas/$slug'
    | '/imoveis/'
    | '/viaturas/'
    | '/api/public/foto/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultor'
    | '/contacto'
    | '/sobre'
    | '/imoveis/$slug'
    | '/viaturas/$slug'
    | '/imoveis'
    | '/viaturas'
    | '/api/public/foto/$'
  id:
    | '__root__'
    | '/'
    | '/consultor'
    | '/contacto'
    | '/sobre'
    | '/imoveis/$slug'
    | '/viaturas/$slug'
    | '/imoveis/'
    | '/viaturas/'
    | '/api/public/foto/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultorRoute: typeof ConsultorRoute
  ContactoRoute: typeof ContactoRoute
  SobreRoute: typeof SobreRoute
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  ViaturasSlugRoute: typeof ViaturasSlugRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
  ViaturasIndexRoute: typeof ViaturasIndexRoute
  ApiPublicFotoSplatRoute: typeof ApiPublicFotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor': {
      id: '/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof ConsultorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/imoveis/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viaturas/': {
      id: '/viaturas/'
      path: '/viaturas'
      fullPath: '/viaturas/'
      preLoaderRoute: typeof ViaturasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viaturas/$slug': {
      id: '/viaturas/$slug'
      path: '/viaturas/$slug'
      fullPath: '/viaturas/$slug'
      preLoaderRoute: typeof ViaturasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/foto/$': {
      id: '/api/public/foto/$'
      path: '/api/public/foto/$'
      fullPath: '/api/public/foto/$'
      preLoaderRoute: typeof ApiPublicFotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultorRoute: ConsultorRoute,
  ContactoRoute: ContactoRoute,
  SobreRoute: SobreRoute,
  ImoveisSlugRoute: ImoveisSlugRoute,
  ViaturasSlugRoute: ViaturasSlugRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
  ViaturasIndexRoute: ViaturasIndexRoute,
  ApiPublicFotoSplatRoute: ApiPublicFotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
